### ISSUE TITLE
cache.WaitForCacheSync may never exit on shutdown

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-autodiscover#41]
This was discovered as the root cause of intermittent failures in the ECK operator integration tests for Fleet. See https://github.com/elastic/cloud-on-k8s/issues/6331#issuecomment-1412761489 for the logs we get when this happens. Diagnostics including a goroutine dump are attached.

Contents of the agent's state.yaml when this happens:

```yaml
components: []
log_level: info
message: context canceled
state: 4
```

[fleet-server-deadlock-diagnostics.tar.gz](https://github.com/elastic/elastic-agent/files/10572102/fleet-server-deadlock-diagnostics.tar.gz)

The coordinator seems to be stuck at:

```
1 @ 0x559a9083e256 0x559a9080c1cc 0x559a9080bbf8 0x559a90ffd2e5 0x559a90ff9c05 0x559a91cb4617 0x559a9086ec61
#	0x559a90ffd2e4	github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner+0x1084	github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:568
#	0x559a90ff9c04	github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).Run+0x164		github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:399
#	0x559a91cb4616	github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run.func6+0x36						github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:220
```

This is the relevant code block:
https://github.com/elastic/elastic-agent/blob/973af90d85dd81aaccfd42a1f81e7ad60f6780db/internal/pkg/agent/application/coordinator/coordinator.go#L552-L568

**Comment by cmacknz** [comment]
We changed the agent so that it will no longer wait forever for the dynamic providers to exit in https://github.com/elastic/elastic-agent/pull/2352. 

I've moved this into the autodiscover repository and reworded the description to specify that this was specifically about cache.WaitForCacheSync not being cancelled on shutdown.

**Comment by gizas** [comment]
Closing this as per https://github.com/elastic/elastic-agent-autodiscover/issues/41#issuecomment-1478328626
