### ISSUE TITLE
Upgrade `github.com/docker/docker` dependency to `v26.0.2+incompatible`

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent-autodiscover#91]
_Taken from https://github.com/elastic/elastic-agent/pull/4615#issuecomment-2103497970:_

In https://github.com/elastic/elastic-agent/pull/4615, we're trying to upgrade the `github.com/elastic/elastic-agent-system-metrics` dependency` from `0.9.2` to `0.9.3`. However, this upgrade is indirectly also upgrading the `github.com/docker/docker` dependency from `v25.0.5+incompatible` to `v26.0.2+incompatible`.

This indirect upgrade is conflicting with the version of the `github.com/elastic/elastic-agent-autodiscover` dependency being used by `github.com/elastic/elastic-agent`: `v0.6.14` because that version depends on an older version of the `github.com/docker/docker` dependency: `v24.0.9+incompatible`.

We need to:
* [x] upgrade the `github.com/docker/docker` dependency to `v26.0.2+incompatible` in this repository
* [x] make the necessary API adjustments (see https://github.com/elastic/elastic-agent/pull/4615#issuecomment-2099462231)
* [x] cut a new release
* [x] upgrade the `github.com/elastic/elastic-agent-autodiscover` dependency in `github.com/elastic/elastic-agent` to the new release's version

This will unblock https://github.com/elastic/elastic-agent/pull/4615.

**Comment by michalpristas** [comment]
closed by #100
