### ISSUE TITLE
Changelog should have latest version first

### ISSUE THREAD

**Issue by andrzej-stencel** [elastic/elastic-agent-autodiscover#94]
The Changelog in this repository is ordered in chronological order (oldest at top), but I think it should be reverse chronological order (latest at top).

I think reverse chronological order is how all Changelogs I've seen are structured. Also [keepachangelog.com](https://keepachangelog.com/) says:

>  - The latest version comes first.

**Comment by cmacknz** [comment]
We stopped maintaining a changelog for support packages like this, because it was basically just a mirror of the commit history which has the correct behavior. GH also auto-generates nice release notes this way.

My vote would be to remove the changelog file.

**Comment by ycombinator** [comment]
Chatted about this in today's team meeting.  Consensus is to remove CHANGELOG files as suggested by @cmacknz in https://github.com/elastic/elastic-agent-autodiscover/issues/94#issuecomment-2145298556.  Closing this issue.
